# Generated by Django 3.0.1 on 2021-08-30 10:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('image', models.ImageField(default='static/users/userDefault1.png', null=True, upload_to='static/users', verbose_name='Avatar')),
                ('referUser', models.UUIDField(null=True)),
                ('fa2', models.BooleanField(default=False, verbose_name='2FA')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
